version: '3.9'
name: spacelens
networks:
  spacelens-net:
    driver: bridge

volumes:
  mongodb-data:
  redis-data:

services:

  redis:
    image: redis:7.2-alpine
    container_name: spacelens-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - spacelens-net
    restart: unless-stopped

  module-be:
    build:
      context: ./MODULE_BE
      dockerfile: Dockerfile
    container_name: spacelens-be
    env_file: .env
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-3000}
      - MONGODB_URI=${MONGODB_URI}
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET}
      - PREFIX_API=${PREFIX_API:-api/v1}
      - SWAGGER_PATH=${SWAGGER_PATH:-docs}
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    depends_on:
      - redis
    networks:
      - spacelens-net
    restart: unless-stopped

  ai-tracking:
    build:
      context: ./MODULE_AI/tracking_service
      dockerfile: Dockerfile
    container_name: ai-tracking-services
    env_file: .env
    environment:
      - AI_PORT=${AI_PORT}
      - REDIS_URL=redis://redis:6379
    ports:
      - "${AI_PORT}:${AI_PORT}"
    volumes:
      - ./MODULE_AI/storage:/app/storage:ro
    depends_on:
      - redis
    networks:
      - spacelens-net
    restart: unless-stopped

  ai-analytics:
    build:
      context: ./MODULE_AI/analytics_service
      dockerfile: Dockerfile
    container_name: ai-analytics-analytics
    env_file: .env
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    networks:
      - spacelens-net
    restart: unless-stopped 


  module-fe:
    build:
      context: ./MODULE_FE
      dockerfile: Dockerfile
    container_name: spacelens-fe
    env_file: ./MODULE_FE/.env
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    ports:
      - "${FE_PORT:-5173}:5173"
    depends_on:
      - module-be
    networks:
      - spacelens-net
    restart: unless-stopped
