name: Backend Test worker
on:
    workflow_call:
        inputs:
            node-version:
                description: "The version Node.js used to project"
                required: false
                default: "20"
                type: string
        outputs:
            status:
                description: " The status is complete of the Backend test"
jobs:
    backend-unit-test:
        name: "Run Nest JS unit test"
        runs-on: ubuntu-latest
        defaults: 
            run:
                working-directory: ./MODULE_BE
        steps:
            - uses: actions/checkout@v4
            - name: Setup node 
              uses: actions/setup-node@v4
              with: 
                node-version: ${{ inputs.node-version }}
                cache: "npm"
                cache-dependency-path: "./MODULE_BE/package-lock.json"
            
            - name: Install dependencies
              run: npm ci
            
            - name: Run test 
              run: npm test

