name: Function Service CI

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string

      service_path:
        required: true
        type: string

    outputs:
      image:
        value: ${{ jobs.ci.outputs.image }}

jobs:
  ci:
    runs-on: ubuntu-latest

    outputs:
      image: ${{ steps.set_image.outputs.image }}

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Get short SHA
        id: vars
        run: |
          SHORT_SHA=$(git rev-parse --short ${{ github.sha }})
          echo "short_sha=${SHORT_SHA}" >> $GITHUB_OUTPUT

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.service_path }}
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.service_name }}:${{ steps.vars.outputs.short_sha }}

      - name: Set Image Output
        id: set_image
        run: |
          echo "image=${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.service_name }}:${{ steps.vars.outputs.short_sha }}" >> $GITHUB_OUTPUT