name: Analysis Service CI

on:
   pull_request:
     branches: ["dev" , "main"]
     paths:
      - 'MODULE_AI/analytics_service/**'
      - '.github/workflows/analysis-service.yml'
      - '.github/workflows/_service-ci.yml'
   push:
    branches: ["dev" , "main"]
    paths:
      - 'MODULE_AI/analytics_service/**'
      - '.github/workflows/analysis-service.yml'
      - '.github/workflows/_service-ci.yml'
concurrency:
    group: analysis-service-${{ github.ref }}
    cancel-in-progress: true
      
jobs:
  ci:
    uses: ./.github/workflows/_service-ci.yml
    with:
      service_name: analysis-service
      service_path: MODULE_AI/analytics_service
    secrets: inherit
    
  deploy:
    needs: ci
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'push' && github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    environment:
      name: production
      url: 
        
    steps:
      - name: Deploy
        run: |
          echo "Deploying..."