name: Tracking Service CI

on:
   pull_request:
     branches: ["dev" , "main"]
     paths:
      - 'MODULE_AI/tracking_service/**'
      - '.github/workflows/tracking-service.yml'
      - '.github/workflows/_service-ci.yml'
   push:
    branches: ["dev" , "main"]
    paths:
      - 'MODULE_AI/tracking_service/**'
      - '.github/workflows/tracking-service.yml'
      - '.github/workflows/_service-ci.yml'
concurrency:
    group: tracking-service-${{ github.ref }}
    cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/_service-ci.yml
    with:
      service_name: tracking-service
      service_path: MODULE_AI/tracking_service
    secrets: inherit

  deploy:
    needs: ci
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'push' && github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    environment:
      name: production
      url:

    steps:
      - name: Deploy
        run: |
          echo "Deploying..."
